spring:
  datasource:
    url: ${MYSQL_MOVIE_DB_URL}
    username: ${MYSQL_MOVIE_DB_USERNAME}
    password: ${MYSQL_MOVIE_DB_PASSWORD}
   
  jpa:
   hibernate:
    ddl-auto: update
   show-sql: true